### ISSUE TITLE
es 5.14

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/Random#2]
![es5_14](https://cloud.githubusercontent.com/assets/3002194/15990502/3bab93d8-3094-11e6-9019-b518de09dae5.png)

**Comment by lucifero55** [comment]
Bisogna modificare il seme per fare questo esercizio?
PS Immagino che non si possano usare if

**Comment by FabioZTessitore** [comment]
il seme va impostato all'inizio come mostrato nei programmi random2 e random3

niente if per risolvere l'esercizio

**Comment by lucifero55** [comment]
Provato a fare la A

**Comment by FabioZTessitore** [comment]
Il seme?

**Comment by lucifero55** [comment]
fatto

**Comment by FabioZTessitore** [comment]
hai provato a compilare ed eseguire? non essere superficiale.
Non c'è il prototipo di time() e i numeri non vengono generati come richiesto

**Comment by lucifero55** [comment]
Provato a risolvere

**Comment by FabioZTessitore** [comment]
alla fine sei riuscito come sempre in un modo piu' complicato del necessario.
Per la cronaca l'insieme 2, 4, 6, 8, 10 è l'insieme dei numeri pari compreso tra 2 e 10. I numeri pari si possono scrivere com 2*n con n compreso tra 1 e 5.
Quindi potevi fare 2*(1+rand()*5)

Una cosa analoga valeva per il secondo gruppo sapendo che i numeri dispari si possono scrivere come 2*n+1
